name: GitHubExplorer

targets:
  GitHubExplorer:
    type: application
    platform: iOS
    sources:
      - path: Sources
    resources:
      - path: Sources/Resource/LaunchScreen.storyboard
      - path: Sources/Resource/Asset.xcassets
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        UILaunchStoryboardName: LaunchScreen

  GitHubExplorerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: GitHubExplorer

  GitHubExplorerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: GitHubExplorer


schemes:
  GitHubExplorer:
    build:
      targets:
        GitHubExplorer: [all]
    test:
      targets:
        - GitHubExplorerTests
        - GitHubExplorerUITests
    run:
      config: Debug

  GitHubExplorerTests:
    build:
      targets:
        GitHubExplorerTests: [all]
    test:
      targets:
        - GitHubExplorerTests
    run:
      config: Debug

  GitHubExplorerUITests:
    build:
      targets:
        GitHubExplorerUITests: [all]
    test:
      targets:
        - GitHubExplorerUITests
    run:
      config: Debug
