
platform :ios do
  desc "Run tests"
  lane :tests do
    scan(
      scheme: "GitHubExplorer",
      devices: ["iPhone 15"],
      clean: true
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    match(type: "appstore")
    build_app(scheme: "GitHubExplorer", export_method: "app-store")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Deploy to App Store"
  lane :release do
    capture_screenshots
    match(type: "appstore")
    build_app(scheme: "GitHubExplorer", export_method: "app-store")
    upload_to_app_store(submit_for_review: true, automatic_release: true)
  end
end
