
name: CI

on:
  pull_request:
    branches: [ develop, release ]
  push:
    branches: [ develop, release ]

jobs:
  build-test-sonar:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install Dependencies
        run: |
          bundle install
          pod install

      - name: Sync Certificates with Match
        run: fastlane match development
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Build & Test
        run: xcodebuild test -scheme GitHubExplorer -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=SEU_ORG
            -Dsonar.projectKey=SEU_PROJECT_KEY
            -Dsonar.sources=.
            -Dsonar.language=swift

      - name: Enforce Sonar Quality Gate
        uses: SonarSource/sonarcloud-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
