name: iOS CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'

    - name: Run SwiftLint (via CocoaPods)
      run: |
         Pods/SwiftLint/swiftlint lint --config .swiftlint.yml
    - name: Run tests
      run: |
        xcodebuild test \
          -scheme GitHubExplorer \
          -project GitHubExplorer.xcodeproj \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 15" \
          -enableCodeCoverage YES | xcpretty

    - name: Post-process test report (add index.html and CNAME)
      run: ./Scripts/post_report.sh
    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports
          publish_branch: gh-pages
